package: sprog
version: '1.0.0-beta3'
author: Thomas Blum
supportpage: www.redaxo.org/de/forum/

page:
    title: 'translate:sprog'
    perm: sprog[]
    pjax: false
    icon: rex-icon rex-icon-language
    subpages:
        wildcard:
            title: 'translate:wildcard'
        copy:
            title: 'translate:copy_content'
            perm: admin[]
            subpages:
                structure_content:
                    title: 'translate:copy_structure_content'
                structure_metadata:
                    title: 'translate:copy_structure_metadata'
        settings:
            title: 'translate:settings'
            perm: admin[]


pages:
    sprog.copy.structure_content_popup:
        title: 'translate:copy_structure_content_popup'
        main: true
        popup: true
        hidden: true
    sprog.copy.structure_content_generate:
        title: 'translate:copy_structure_content_generate'
        main: true
        hasLayout: false
        hidden: true
    sprog.copy.structure_metadata_popup:
        title: 'translate:copy_structure_metadata_popup'
        main: true
        popup: true
        hidden: true
    sprog.copy.structure_metadata_generate:
        title: 'translate:copy_structure_metadata_generate'
        main: true
        hasLayout: false
        hidden: true
