package: sprog
version: '1.0.0-beta1'
author: Thomas Blum
supportpage: www.redaxo.org/de/forum/

page:
    title: 'translate:sprog'
    perm: sprog[]
    pjax: false
    icon: rex-icon rex-icon-language
    subpages:
        wildcard: { title: 'translate:wildcard' }
        settings:
            title: 'translate:settings'
            perm: admin[]
